[[redirects]]
  from = "https://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = false
[[redirects]]
  from = "https://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = false
[[redirects]]
  from = "https://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = false
[[redirects]]
  from = "https://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = false
