[[redirects]]
  from = "https://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.com/training"
  to = "https://www.unstarvingartists.com/training"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.com/training"
  to = "https://www.unstarvingartists.com/training"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/stories"
  to = "https://www.unstarvingartists.com/reviews"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/stories/:student"
  to = "https://www.unstarvingartists.com/reviews/:student"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/bryce-art"
  to = "https://www.unstarvingartists.com/blog/bryce-art"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/bryce"
  to = "https://www.unstarvingartists.com/blog/bryce"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/charlie"
  to = "https://www.unstarvingartists.com/blog/charlie"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/chaz"
  to = "https://www.unstarvingartists.com/blog/chaz"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/cherie"
  to = "https://www.unstarvingartists.com/blog/cherie"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/christian"
  to = "https://www.unstarvingartists.com/blog/christian"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/dorit"
  to = "https://www.unstarvingartists.com/blog/dorit"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/elias"
  to = "https://www.unstarvingartists.com/blog/elias"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/evan"
  to = "https://www.unstarvingartists.com/blog/evan"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/filipe"
  to = "https://www.unstarvingartists.com/blog/filipe"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/jason"
  to = "https://www.unstarvingartists.com/blog/jason"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/jawad"
  to = "https://www.unstarvingartists.com/blog/jawad"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/jeff"
  to = "https://www.unstarvingartists.com/blog/jeff"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/kate"
  to = "https://www.unstarvingartists.com/blog/kate"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/kelly-30k"
  to = "https://www.unstarvingartists.com/blog/kelly-30k"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/kelly-gordon"
  to = "https://www.unstarvingartists.com/blog/kelly-gordon"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/keval"
  to = "https://www.unstarvingartists.com/blog/keval"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/khierstyn"
  to = "https://www.unstarvingartists.com/blog/khierstyn"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/marek"
  to = "https://www.unstarvingartists.com/blog/marek"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/michael"
  to = "https://www.unstarvingartists.com/blog/michael"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/oliver"
  to = "https://www.unstarvingartists.com/blog/oliver"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/pedro"
  to = "https://www.unstarvingartists.com/blog/pedro"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/peter"
  to = "https://www.unstarvingartists.com/blog/peter"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/preston"
  to = "https://www.unstarvingartists.com/blog/preston"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/scott"
  to = "https://www.unstarvingartists.com/blog/scott"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/sharif"
  to = "https://www.unstarvingartists.com/blog/sharif"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/stefan"
  to = "https://www.unstarvingartists.com/blog/stefan"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/vigdis"
  to = "https://www.unstarvingartists.com/blog/vigdis"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/viktor"
  to = "https://www.unstarvingartists.com/blog/viktor"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/reviews/vince"
  to = "https://www.unstarvingartists.com/blog/vince"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/training"
  to = "https://go.unstarvingartists.com/training"
  status = 302
  force = true
