[[redirects]]
  from = "https://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true

[[headers]]
  for = "/stories/keval/"
  [headers.values]
    X-Robots-Tag = "noindex"
