[[redirects]]
  from = "https://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://www.unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://www.unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.com/training"
  to = "https://www.unstarvingartists.com/training"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.com/training"
  to = "https://www.unstarvingartists.com/training"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/stories"
  to = "https://www.unstarvingartists.com/reviews"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/stories/:student"
  to = "https://www.unstarvingartists.com/reviews/:student"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/training"
  to = "https://go.unstarvingartists.com/training"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/partner"
  to = "https://join.unstarvingartists.com/partner"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/partner*"
  to = "https://join.unstarvingartists.com/partner"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/start"
  to = "https://start.unstarvingartists.com/partner1671386235222"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/start*"
  to = "https://start.unstarvingartists.com/partner1671386235222"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/o/agreement"
  query = {utm_campaign = ":utm_campaign"}
  to = "https://www.unstarvingartists.com/:utm_campaign/agreement"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/migrate/agreement"
  to = "https://www.skool.com/the-academy/"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/catalyst"
  to = "https://get.unstarvingartists.com/community"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/community"
  to = "https://get.unstarvingartists.com/community"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/start/agreement"
  to = "https://start.unstarvingartists.com/agreement1671386243769"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/join/agreement"
  to = "https://join.unstarvingartists.com/agreement1660492693399"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/orientation"
  to = "https://join.unstarvingartists.com/orientation"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/flywheel-lab"
  to = "https://www.unstarvingartists.com/academy"
  status = 301
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/orientation*"
  to = "https://join.unstarvingartists.com/orientation"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/workshop"
  to = "https://join.unstarvingartists.com/workshop"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/kelly-gordon"
  to = "https://www.unstarvingartists.com/kelly-g"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/workshop*"
  to = "https://join.unstarvingartists.com/workshop"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/li/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=linkedin"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/migrate"
  to = "https://join.unstarvingartists.com/migrate"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/cs/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=cheatsheet"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/li/workshop*"
  to = "https://join.unstarvingartists.com/workshop?el=linkedin"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/ig/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=instagram"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/ig/workshop*"
  to = "https://join.unstarvingartists.com/workshop?el=instagram"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/fb/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=facebook"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/twi/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=twitch"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/yt/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=youtube"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/tw/workshop"
  to = "https://join.unstarvingartists.com/workshop?el=twitter"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/tw/workshop*"
  to = "https://join.unstarvingartists.com/workshop?el=twitter"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/agreement"
  to = "https://join.unstarvingartists.com/agreement"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/agreement*"
  to = "https://join.unstarvingartists.com/agreement"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/success"
  to = "https://calendly.com/unstarvingartists/1on1-success"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/call"
  to = "https://calendly.com/harrywhelchel/discovery"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/stripe"
  to = "https://stripe.com/payments/features#dashboard-mobile-app"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/success*"
  to = "https://calendly.com/unstarvingartists/1on1-success"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/bonuses"
  to = "https://join.unstarvingartists.com/bonuses"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/flick*"
  to = "https://flick.tech?fpr=unstarvingartists"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/hotline"
  to = "https://www.videoask.com/fv73s5zkc"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/saatchi*"
  to = "https://www.saatchiart.com/"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/book"
  to = "https://book.unstarvingartists.com/offer?el=wordofmouth&htrafficsource=wordofmouth"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/tw/book"
  to = "https://book.unstarvingartists.com/offer?el=twitter&htrafficsource=twitter"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/ig/book"
  to = "https://book.unstarvingartists.com/offer?el=instagram&htrafficsource=instagram"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/fb/book"
  to = "https://book.unstarvingartists.com/offer?el=facebook&htrafficsource=facebook"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/li/book"
  to = "https://book.unstarvingartists.com/offer?el=linkedin&htrafficsource=linkedin"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/yt/book"
  to = "https://book.unstarvingartists.com/offer?el=youtube&htrafficsource=youtube"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/twi/book"
  to = "https://book.unstarvingartists.com/offer?el=twitch&htrafficsource=twitch"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/st/book"
  to = "https://book.unstarvingartists.com/offer?el=substack&htrafficsource=substack"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/rs/book"
  to = "https://book.unstarvingartists.com/offer?el=restream"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/ls/book"
  to = "https://book.unstarvingartists.com/offer?el=livestream&htrafficsource=livestream"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/tp/book"
  to = "https://book.unstarvingartists.com/offer?el=trustpilot&htrafficsource=trustpilot"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/go/book"
  to = "https://book.unstarvingartists.com/offer?el=google&htrafficsource=google"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/pc/book"
  to = "https://book.unstarvingartists.com/offer?el=podcast&htrafficsource=podcast"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/tp"
  to = "https://www.unstarvingartists.com?el=trustpilot&htrafficsource=trustpilot"
  status = 302
  force = true
[[redirects]]
  from = "https://www.unstarvingartists.com/go"
  to = "https://www.unstarvingartists.com?el=google&htrafficsource=google"
  status = 302
  force = true
[[redirects]]
  from = "https://unstarvingartist.com/*"
  to = "https://www.unstarvingartists.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartist.com/*"
  to = "https://www.unstarvingartists.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "https://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://unstarvingartists.org/*"
  to = "https://www.unstarvingartists.com/:splat"
  status = 301
  force = true
